/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mymoney.ui;

import com.mymoney.dao.LoaiThuDAO;
import com.mymoney.entity.LoaiThu;
import com.mymoney.helper.DataValidator;
import com.mymoney.utils.Auth;
import com.mymoney.utils.MsgBox;
import com.mymoney.utils.XImage;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lam
 */
public class GioiHanChiTieuJPanel extends javax.swing.JPanel {

    JFileChooser fileChooser = new JFileChooser();
    LoaiThuDAO dao = new LoaiThuDAO();
    int row = 0;

    /**
     * Creates new form KhoanThuJPanel
     */
    public GioiHanChiTieuJPanel() {
        initComponents();
        init();
    }

    void init() {
        fillPanel();

    }

    public void fillPanel() {

        JPanel p = new JPanel(new BorderLayout()); //Nên dùng cách này

        try {
            int i = 1;
            List<LoaiThu> list = dao.selectByTaiKhoan(Auth.user.getMaTK());
            for (LoaiThu lt : list) {
                Object[] row = {
                    i++,
                    lt.getMaLT(),
                    lt.getTenLT(),
                    lt.getHinhLT(),
                    
                
                };

                


            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liêu");
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnGHCT = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIỚI HẠN CHI TIÊU");

        javax.swing.GroupLayout pnGHCTLayout = new javax.swing.GroupLayout(pnGHCT);
        pnGHCT.setLayout(pnGHCTLayout);
        pnGHCTLayout.setHorizontalGroup(
            pnGHCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnGHCTLayout.setVerticalGroup(
            pnGHCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addComponent(pnGHCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnGHCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnGHCT;
    // End of variables declaration//GEN-END:variables
}
