/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mymoney.ui;

import com.mymoney.utils.Auth;
import com.mymoney.utils.MsgBox;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JPanel;

/**
 *
 * @author lam
 */
public class QuanLyJPanel extends javax.swing.JPanel {
    private JPanel chilJPanel; 
    /**
     * Creates new form QuanLyJPanel
     */
    public QuanLyJPanel() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnKhoanThu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnKhoanChi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnLoaiThu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnLoaiChi = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnTietKiem = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        pnMainQL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setBackground(new java.awt.Color(110, 89, 222));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnKhoanThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mymoney/icon/Download.png"))); // NOI18N
        btnKhoanThu.setText("KHOẢN THU");
        btnKhoanThu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhoanThu.setFocusable(false);
        btnKhoanThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoanThu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoanThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoanThuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoanThu);
        jToolBar1.add(jSeparator2);

        btnKhoanChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mymoney/icon/Remove from basket.png"))); // NOI18N
        btnKhoanChi.setText("KHOẢN CHI");
        btnKhoanChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhoanChi.setFocusable(false);
        btnKhoanChi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoanChi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoanChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoanChiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoanChi);
        jToolBar1.add(jSeparator1);

        btnLoaiThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mymoney/icon/Card file.png"))); // NOI18N
        btnLoaiThu.setText("LOẠI THU");
        btnLoaiThu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoaiThu.setFocusable(false);
        btnLoaiThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoaiThu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoaiThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiThuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoaiThu);
        jToolBar1.add(jSeparator3);

        btnLoaiChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mymoney/icon/Cash register.png"))); // NOI18N
        btnLoaiChi.setText("LOẠI CHI");
        btnLoaiChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoaiChi.setFocusable(false);
        btnLoaiChi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoaiChi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoaiChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiChiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoaiChi);
        jToolBar1.add(jSeparator4);

        btnTietKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mymoney/icon/Piggy bank.png"))); // NOI18N
        btnTietKiem.setText("TIẾT KIỆM");
        btnTietKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTietKiem.setFocusable(false);
        btnTietKiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTietKiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTietKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTietKiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTietKiem);
        jToolBar1.add(jSeparator5);

        pnMainQL.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(110, 89, 222));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mymoney/icon/stock1.png"))); // NOI18N
        pnMainQL.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
            .addComponent(pnMainQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMainQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhoanThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoanThuActionPerformed
        // TODO add your handling code here:
         if (Auth.isLogin()) {
            chilJPanel = new KhoanThuJPanel();
            pnMainQL.removeAll();
            pnMainQL.add(chilJPanel);

          

            pnMainQL.validate();
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
       
    }//GEN-LAST:event_btnKhoanThuActionPerformed

    private void btnKhoanChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoanChiActionPerformed
        // TODO add your handling code here:
         if (Auth.isLogin()) {
            chilJPanel = new KhoanChiJPanel();
            pnMainQL.removeAll();
            pnMainQL.add(chilJPanel);
            pnMainQL.validate();
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
       ;
    }//GEN-LAST:event_btnKhoanChiActionPerformed

    private void btnLoaiThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiThuActionPerformed
        // TODO add your handling code here:
         if (Auth.isLogin()) {
            chilJPanel = new LoaiThuJPanel();
            pnMainQL.removeAll();
            pnMainQL.add(chilJPanel);
            pnMainQL.validate();
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
         
        
    }//GEN-LAST:event_btnLoaiThuActionPerformed

    private void btnLoaiChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiChiActionPerformed
        // TODO add your handling code here:
         if (Auth.isLogin()) {
            chilJPanel = new LoaiChiJPanel();
            pnMainQL.removeAll();
            pnMainQL.add(chilJPanel);
            pnMainQL.validate();
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_btnLoaiChiActionPerformed

    private void btnTietKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTietKiemActionPerformed
        // TODO add your handling code here:
         if (Auth.isLogin()) {
            chilJPanel = new TietKiemJPanel();
            pnMainQL.removeAll();
            pnMainQL.add(chilJPanel);
            pnMainQL.validate();
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_btnTietKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoanChi;
    private javax.swing.JButton btnKhoanThu;
    private javax.swing.JButton btnLoaiChi;
    private javax.swing.JButton btnLoaiThu;
    private javax.swing.JButton btnTietKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnMainQL;
    // End of variables declaration//GEN-END:variables
}
